Default to "eu-west-1" on .env.example
The region needs to be valid, otherwise the tests fail with:

```
ValueError: Invalid endpoint: https://lambda.change_me.amazonaws.com
```

By having a valid region by default, we make it a tiny bit easier for users.