Fix Docker build
At some point Alpine switched from openssl to libressl. For some reason
this caused an error to appear during last week:

    Step 17/24 : RUN apk add [...]

     ---> Running in 52e7e742d29e
    fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
    fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
    ERROR: unsatisfiable constraints:
      openssl-dev-1.0.2o-r0:
	conflicts:
		   libressl-dev-2.6.3-r0[pc:libcrypto=1.0.2o]
		   libressl-dev-2.6.3-r0[pc:libssl=1.0.2o]
		   libressl-dev-2.6.3-r0[pc:openssl=1.0.2o]
      libressl-dev-2.6.3-r0:
	conflicts:
		   openssl-dev-1.0.2o-r0[pc:libcrypto=2.6.3]
		   openssl-dev-1.0.2o-r0[pc:libssl=2.6.3]
		   openssl-dev-1.0.2o-r0[pc:openssl=2.6.3]
	satisfies:
		   postgresql-dev-10.4-r0[libressl-dev]
      build-dependencies-0:
	masked in: cache
	satisfies: world[build-dependencies]

Switching to libressl solved that issue but the the cryptography python package
build was failing:

    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python3.5m -c build/temp.linux-x86_64-3.5/_openssl.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/_openssl.o
    In file included from /usr/include/openssl/x509.h:595:0,
                     from /usr/include/openssl/engine.h:96,
                     from build/temp.linux-x86_64-3.5/_openssl.c:567:
    build/temp.linux-x86_64-3.5/_openssl.c:3467:19: error: expected identifier or '(' before numeric constant
     static const long X509_V_ERR_HOSTNAME_MISMATCH = 0;
                       ^
    build/temp.linux-x86_64-3.5/_openssl.c:3468:19: error: expected identifier or '(' before numeric constant
     static const long X509_V_ERR_EMAIL_MISMATCH = 0;
                       ^
    build/temp.linux-x86_64-3.5/_openssl.c:3469:19: error: expected identifier or '(' before numeric constant
     static const long X509_V_ERR_IP_ADDRESS_MISMATCH = 0;
                       ^
    error: command 'gcc' failed with exit status 1

Upgrading to the latest version solved the issue and the Docker build now works.